### ISSUE TITLE
[Bug] Certificate chain issue 

### ISSUE THREAD

**Issue by PatrickSt1991** [PatrickSt1991/Samsung-Jellyfin-Installer#118]
![tizen error](https://github.com/user-attachments/assets/5e541fad-a9fc-41b9-87ad-3685e5d83729)

_Originally posted by @vincom in https://github.com/PatrickSt1991/Samsung-Jellyfin-Installer/discussions/117_

Looks like this time it's the author Certificate

**Comment by PatrickSt1991** [comment]
Fixed in [v1.8.3.5](https://github.com/PatrickSt1991/Samsung-Jellyfin-Installer/releases/tag/v1.8.3.5)

**Comment by DouglasMarq** [comment]
Hello @PatrickSt1991

I'm on 1.8.3.5 and the bug persists:

<img width="990" height="460" alt="Image" src="https://github.com/user-attachments/assets/b0a6a26a-dee4-4530-ae4e-a27c8952787c" />

**Comment by PatrickSt1991** [comment]
@DouglasMarq first time you've ever used the tool? can you send over these files please;
C:\Users\Douglas\AppData\Local\Programs\TizenStudioCli-data\profile\profiles.xml

and please zip this folder and send it as well;
C:\Users\Douglas\SamsungCertificate\Jelly2Sams

patrick@madebypatrick.nl

**Comment by PatrickSt1991** [comment]
@DouglasMarq also just released a new beta version that no longer requires any Samsung Tizen Studio software

[v1.8.3.6-beta](https://github.com/PatrickSt1991/Samsung-Jellyfin-Installer/releases/tag/v1.8.3.6-beta)

**Comment by DouglasMarq** [comment]
@PatrickSt1991 thanks for the quick reply. It is my first time ever using this tool.

The beta one worked on both my TV. So i had this issue:

The first time that i tried to install failed, for some reason it was using my install of tizen studio, which i uninstalled and it correctly installed jellyfin on the first TV (UN55CU7700GXZD), probably was having certificate conflict.

But it didnt work at my second TV (UN65RU7100GXZD). I've just tested the beta one with both my TV and it installed wonderfully.
I'll send you the files if you wanna check it.

**Comment by PatrickSt1991** [comment]
If the beta version worked it's fine, that version is free of tizen software and probably the reason the conflict was gone aswell
