### ISSUE TITLE
Error: sdb sync fail UNKNOWN

### ISSUE THREAD

**Issue by destiezk** [PatrickSt1991/Samsung-Jellyfin-Installer#135]
Hello,
I'm having the issue shown on the picture. I'd install it to a Samsung TV which is fairly old (running Tizen 2.4(?), however the TV appears, and install with permit is checked as well. TV has Developer Mode enabled as well.

Thanks in advance!

<img width="634" height="306" alt="Image" src="https://github.com/user-attachments/assets/3191c0b0-63e4-42d0-abf1-6b30b83095e1" />

**Comment by PatrickSt1991** [comment]
@destiezk I'll hopefully release a beta version tomorrow containing a fix for the permit install

**Comment by PatrickSt1991** [comment]
@destiezk try this beta release [v1.8.4.3-beta](https://github.com/PatrickSt1991/Samsung-Jellyfin-Installer/releases/tag/v1.8.4.3-beta) I fixed the permit install for older Tizen models, if it still doesn't work please also enable the new feature in settings page **Show SDB Output**

**Comment by WinMinerGMX** [comment]
Great tool if it works. I am getting the same error though on my now old Samsung TV UE70KU6079. Tried the [v1.8.4.3-beta](https://github.com/PatrickSt1991/Samsung-Jellyfin-Installer/releases/tag/v1.8.4.3-beta) but got another error.

<img width="1007" height="442" alt="Image" src="https://github.com/user-attachments/assets/5192bfb5-312a-4ab3-8182-8078714c3f7f" />

I tried with Tizen < 4.0 Option since I don't know the version of my TV but it is pretty old now (bought in 2016).
Also activated the SDB Output on the second run. 

Logs attached.
[logs.zip](https://github.com/user-attachments/files/23279438/logs.zip)

**Comment by PatrickSt1991** [comment]
I'll look into it, your Tizen OS is probably 2.4

**Comment by PatrickSt1991** [comment]
@WinMinerGMX @destiezk the latest beta release [v1.8.4.6-beta](https://github.com/PatrickSt1991/Samsung-Jellyfin-Installer/releases/tag/v1.8.4.6-beta) fixes the path1 error.

**Comment by WinMinerGMX** [comment]
@PatrickSt1991 - I will try v1.8.4.6-beta now. Thank you!

I am still getting an error.

<img width="1007" height="442" alt="Image" src="https://github.com/user-attachments/assets/7cc2b955-4c17-4379-bbf6-ff4594e81b58" />

New logs:
[logs_Jellyfin2Samsung-v1.8.4.6-beta-win-x64.zip](https://github.com/user-attachments/files/23285957/logs_Jellyfin2Samsung-v1.8.4.6-beta-win-x64.zip)

Does ist matter which version I chose (i.e. Greyfix vs Oblong vs TrueHD)? I don't think my TV has any of these features. As I understand the Oblong version just fixes how the app icon is displayed on the screen (oblong tile vs more quadratic one).

**Comment by PatrickSt1991** [comment]
@WinMinerGMX ah that sucks, at least it's not the path error anymore, it looks like the permit-install command worked.
```
* Pushing device-profile.xml to 192.168.178.30...
Pushing C:\Users\MightyHans\Downloads\Jellyfin2Samsung-v1.8.4.6-beta-win-x64\Assets\Certificate\Jelly2Sams\device-profile.xml to /home/developer/device-profile.xml
Push complete.
* Push completed successfully
```

so the device-profile.xml is pushed to your TV, but now the SDB connection failed as it seems cause there was no response.

Can you try again? in the meanwhile I'll try and see if I can change anything in the SDB connection

No doesn't really matter what version you'll take

**Comment by WinMinerGMX** [comment]
I've tried again but it always fails. I also tried to manually use TizenSdb_v1.0.5.exe but I don't really know what I am doing. Seems like TizenSdb_v1.0.5.exe connect 192.168.178.30 always fails.

<img width="979" height="512" alt="Image" src="https://github.com/user-attachments/assets/9480d9c7-07d8-49a3-b5a8-ecc035e8e3c9" />

I enabled developer mode and set the host IP to the IP of my laptop via the remote. Not sure if this information helps.

**Comment by PatrickSt1991** [comment]
@WinMinerGMX connection works as it seems cause the DUID returns a value but your TV isn't allowing anything else.

I wonder what will happen if you do this.

1. Go to [Jellyfin Releases](https://github.com/jeppevinkel/jellyfin-tizen-builds/releases).
2. From the Assets list download the Jellyfin WGT file you want.
3. Open command prompt.
4.Navigate to your folder containing the SDB Client: `cd c:\Users\MightyHans\Downloads\Jellyfin2Samsung-v1.8.4.6-beta-win-x64\Assets\TizenSDB`
5. Execute the install command `TizenSdb_v1.0.5.exe install 192.168.178.30 C:\Users\MightyHans\Downloads\Jellyfin.wgt` -> This C:\Users location should be your location where the downloaded file is
What's the output from step 5?

If step 5 results in a error do this command `TizenSdb_v1.0.5.exe permit-install 192.168.178.30 c:\Users\MightyHans\Downloads\Jellyfin2Samsung-v1.8.4.6-beta-win-x64\Assets\Certificate\Jelly2Sams\device-profile.xml`

What does that returns? if its a good return, try step 5 again


Of course please check the paths

**Comment by WinMinerGMX** [comment]
Thanks for nailing the paths. Less work for me to type them out. They should be all good. Sadly I get the same error again.

<img width="993" height="555" alt="Image" src="https://github.com/user-attachments/assets/653bee3e-e9f0-4aa3-8ac1-698e46486e41" />

I have never used my TV with a Samsung account. I will try to set one upm use the force login setting an see if that makes a difference.

**Comment by PatrickSt1991** [comment]
@WinMinerGMX what do you mean? you don't have a Samsung account? then how is the certificate generated?

**Comment by WinMinerGMX** [comment]
@PatrickSt1991 

I have a Samsung account back from when I had a Samsung smartphone. What I meant is, that I have never used the TV to log into this account. I did this now, but the issue remains unchanged. 

Nonetheless I probably had some misconceptions how your tool works and thought that it just uses the provided cert to sign anything. Can I verify if the cert is generated at all?

**Comment by PatrickSt1991** [comment]
@WinMinerGMX ahh okay, yeah the certificate is created, otherwise the device-profile.xml won't be present as well.

The tricky bit here is letting your TV know it's okay to install the WGT app, on newer models this isn't necessary anymore and you just sign the wgt install it and that's that, 

I'll take another look into the official software what they are doing, cause it's just weird that you are getting this;

<img width="258" height="44" alt="Image" src="https://github.com/user-attachments/assets/bf356e99-f9aa-4e68-ba29-0201bf9a55be" />

**Comment by WinMinerGMX** [comment]
@PatrickSt1991 - I tried the more manual route laid out [here](https://github.com/jeppevinkel/jellyfin-tizen-builds/blob/master/README.md) by jeppevinkel and I am happy to report that this seems to have worked.

<img width="1225" height="741" alt="Image" src="https://github.com/user-attachments/assets/472652b1-9de2-4c6c-863e-58d2e55fbe68" />

**Comment by PatrickSt1991** [comment]
> @PatrickSt1991 - I tried the more manual route laid out [here](https://github.com/jeppevinkel/jellyfin-tizen-builds/blob/master/README.md) by jeppevinkel and I am happy to report that this seems to have worked.
> 
> <img width="1225" height="741" alt="Image" src="https://github.com/user-attachments/assets/472652b1-9de2-4c6c-863e-58d2e55fbe68" />
> 

Great to hear, using the official Tizen Studio did the trick, i will still dive into this cause I really dislike the official studio stuff, it's bulky and lagy.

But at least you got jellyfin

**Comment by WinMinerGMX** [comment]
@PatrickSt1991 - that's why I was glad to find your tool to be honest. It seems much easier, but in the end it wasn't so bad to go the other route. Please let me know when you need help testing new builds. I would be glad to help out to squash this issue.

**Comment by PatrickSt1991** [comment]
@WinMinerGMX thanks that's really nice from you!

Can you run this command from TizenSdb.exe?

`TizenSdb_v1.0.5.exe capability  192.168.178.30`

I wonder what the return is, cause I think I finally found what's wrong, but that return can confirm or deny it haha

**Comment by WinMinerGMX** [comment]
@PatrickSt1991 - Here you go.

<img width="1225" height="741" alt="Image" src="https://github.com/user-attachments/assets/30e59b66-ead9-418c-ba85-1b373e788698" />

**Comment by PatrickSt1991** [comment]
@WinMinerGMX amazing stuff, the old Tizen OS doesn't returns the sdk_toolpath that the new OS does, but at the same time that's also a good way to set the legacy path hardcoded.

So I created a new build [v1.8.4.8](https://github.com/PatrickSt1991/Samsung-Jellyfin-Installer/releases/tag/v1.8.4.8) and also a update to the TizenSdb client, that new combination should work

**Comment by WinMinerGMX** [comment]
@PatrickSt1991 - Still getting the same error.

<img width="1005" height="442" alt="Image" src="https://github.com/user-attachments/assets/b8b45a03-1a1d-424c-b4eb-7f55fca182d2" />

Logs here. [logs-Jellyfin2Samsung-v1.8.4.8-win-x64.zip](https://github.com/user-attachments/files/23315631/logs-Jellyfin2Samsung-v1.8.4.8-win-x64.zip)

**Comment by PatrickSt1991** [comment]
@WinMinerGMX o f*ck I only made the path dynamic for the permit-install function in the SDB client.

Forgot I also had to do it for the actual install function.

```

    public async Task InstallApp()
    {
        if (string.IsNullOrEmpty(_packagePath))
            throw new InvalidOperationException("Package path not set.");

        string remotePath = $"/home/owner/share/tmp/sdk_tools/tmp/{Path.GetFileName(_packagePath)}";

        // Find the package ID on the device
        string appId = await FindPackageId();

        // Open package file as a stream and push it
        await using var fs = File.OpenRead(_packagePath);
        await _sdbClient.PushAsync(fs, remotePath);

        // Install the app via shell command
        await foreach (string line in _sdbClient.ShellCommandLinesAsync($"0 vd_appinstall {appId} {remotePath}"))
        {
            // Optional logging:
            Console.WriteLine(line);
        }
    }
```

I'll do that tomorrow and bring out yet another build, thanks for all your testing and helping out!

**Comment by PatrickSt1991** [comment]
@WinMinerGMX what about this one [v1.8.5.0](https://github.com/PatrickSt1991/Samsung-Jellyfin-Installer/releases/tag/v1.8.5.0) now the installation path is also dynamically determined

**Comment by WinMinerGMX** [comment]
Hi @PatrickSt1991 - will try now. Sorry today was a bit more busy with my day to day job and sports. Will update the post once I have tested the new version.

This is interesting. It says, install complete but still errors out in a way.

<img width="582" height="442" alt="Image" src="https://github.com/user-attachments/assets/f7d5eada-6af0-492f-add5-817edf0f68c7" />

[logs-Jellyfin2Samsung-v1.8.5.0-win-x64.zip](https://github.com/user-attachments/files/23344699/logs-Jellyfin2Samsung-v1.8.5.0-win-x64.zip)

**Comment by WinMinerGMX** [comment]
@PatrickSt1991 - I've checked on my TV but it looks like the 10.10.Oblong version I installed with the Tizen Studio is still present. I will try to find out how to remove it with Tizen Studio and then try again.

Update:
It was easier to remove the app via the app center in of the TV via the remote. I removed the old 10.10.Oblong and tried again and despite the error I am happy to report that it successfully installed 10.11.Oblong. So it works but throws a bunch of errors.

What didn't work was pre-configuring my server IP that I've set in the Jellyfin Config section of your tool, however I didn't chose an Update mode since I have no idea what to chose here or what the actual modes are doing. My assumption was, that if I enter my server IP here (192.168.178.133) that it would automatically apply that on first boot of the app on the TV. 

I've tried to install the 10.11.secondary version here ... which also worked. Logs of successful attempt attached down below.
[logs-successful-Jellyfin2Samsung-v1.8.5.0-win-x64.zip](https://github.com/user-attachments/files/23345028/logs-successful-Jellyfin2Samsung-v1.8.5.0-win-x64.zip)

**Comment by PatrickSt1991** [comment]
@WinMinerGMX thanks for all your testing!

The config section needs a bit of work I guess, if you don't choose an update mode then nothing will change or be set.

I'll think of something more natural or self explaining, or maybe you got a cool idea?

I'll check the logs tomorrow and maybe I can capture the output so it won't throw the error

**Comment by PatrickSt1991** [comment]
So apparently the older installation method reports:

```
app_id[JepZAARz4r.Jellyfin] install start
app_id[JepZAARz4r.Jellyfin] install conpleted
```

While the newer versions report 
```
app_id[JepZAARz4r.Jellyfin] install 100% completed
```

Thats why you still saw the errors, I'll fix that in a upcoming release and I will also take a look at that uninstall command

**Comment by PatrickSt1991** [comment]
@WinMinerGMX I've implemented the capture of the install completed return so now after install you'll get no more errors.

As this issue is now resolved can we close this issue? and maybe open a new feature request to improve the Jellyfin Config window if needed?

**Comment by WinMinerGMX** [comment]
@PatrickSt1991 - I've tested Jellyfin2Samsung-v1.8.5.1-win-x64 but I am still getting the error indication.

<img width="1004" height="442" alt="Image" src="https://github.com/user-attachments/assets/0f9c075f-672f-4068-9ed0-9711d0583cb3" />

The installation however works if I manually remove the old Jellyfin installation beforehand.

We can move to a new ticket if you want to or we can also engage in more direct communication if you want to.

**Comment by PatrickSt1991** [comment]
Hmm that's weird, so the error window says install failed with error code 118 but it did install correctly?!

What does the log file says?

Well let's continue this issue, easier for people who get the same issue 

Or is that error coming when you try to install with the old version still installed?

**Comment by PatrickSt1991** [comment]
@WinMinerGMX what I find wierd it, when you install **Jellyfin-10.11.z-secondary.wgt** it returns
```
app_id[JepZAARz4r.Jellyfin] install start
app_id[JepZAARz4r.Jellyfin] install completed
```

but when you install **Jellyfin-10.10.z-TrueHD.wgt** it returns
```
app_id[AprZAARz4r.Jellyfin] install start
app_id[AprZAARz4r.Jellyfin] install failed[118]
```

So what's the difference between those two.

**Comment by WinMinerGMX** [comment]
@PatrickSt1991 - I think the difference between those attempts might have been that when I tried to install TrueHD that I was hoping for the automatic uninstall option to work and Oblong was probably alread installed. The secondary naturally installed without a problem since it installs as a separate app and wasn't previously installed either. So far only manual removal (via the TV App Menu) of the Jellyfin apps has worked for me. I can test later again with more clearly labled log files.

**Comment by PatrickSt1991** [comment]
@WinMinerGMX I also found another bug in the code, and created a beta release for it;
[v1.8.5.2-beta](https://github.com/PatrickSt1991/Samsung-Jellyfin-Installer/releases/tag/v1.8.5.2-beta) this one pushes device-profile.xml to /home/developer, but the package to /usr/opt/.... location.

You did permit-install through Tizen Studio also once right? so maybe that also has something to do with it

**Comment by WinMinerGMX** [comment]
@PatrickSt1991 - Yes I did whatever this bat file / command does **c:\tizen-studio\tools\ide\bin\tizen.bat install -n Jellyfin.wgt -t <the name of your tv>**.

**Comment by WinMinerGMX** [comment]
@PatrickSt1991 - I've tested v1.8.5.2-beta now with the following conditions:

- all Jellyfin apps were manually removed before running your tool.
- installation was successful but the error message is still thrown.

<img width="1008" height="441" alt="Image" src="https://github.com/user-attachments/assets/945d448e-00ce-4559-b006-94e7a5c1e6da" />

Logs:

[logs-Jellyfin2Samsung-v1.8.5.2-beta-win-x64.zip](https://github.com/user-attachments/files/23397708/logs-Jellyfin2Samsung-v1.8.5.2-beta-win-x64.zip)

**Comment by PatrickSt1991** [comment]
Thats progress, its not failed anymore it literally says install complete.

I just need to capture that and process it so it won't show the error window

**Comment by PatrickSt1991** [comment]
I'll try and make another beta release today, that handles that return

**Comment by PatrickSt1991** [comment]
@WinMinerGMX this version should show a success window instead of the error window
[v1.8.5.3-beta](https://github.com/PatrickSt1991/Samsung-Jellyfin-Installer/releases/tag/v1.8.5.3-beta)

**Comment by WinMinerGMX** [comment]
I've just tested 1.8.5.4 and can confirm that it works **and looks pretty now** (no error message). :D

[destiezk](https://github.com/destiezk) - you should try again with v1.8.5.4

**Comment by PatrickSt1991** [comment]
@WinMinerGMX thanks for sticking around and helping out with all the test builds!
