### ISSUE TITLE
[Feature] updating existing Jellyfin-Tizen install

### ISSUE THREAD

**Issue by mjeshurun** [PatrickSt1991/Samsung-Jellyfin-Installer#167]
**Feature Description**  
Will it possible to install new Jellyfin-Tizen versions on top of an older version already installed on the TV?

**Why Is This Feature Useful?**  
Currently, running the installer fails if Jellyfin is already installed on the TV. 
I prefer not to delete the previous version, because deleting it would mean to setup the whole Jellyfin TV app from scratch including logging in, which isn't so comfortable on a TV. 

**Additional Context**  

<img width="576" height="433" alt="Image" src="https://github.com/user-attachments/assets/69f94928-d21b-499f-a640-f5c0f10fb145" />

**Comment by PatrickSt1991** [comment]
@mjeshurun no unfortunately not, you can only over write the app with the new app if the author certificate matches (in most cases it won't cause the previous installation wasn't done by this tool, so I never bothered to build it in), when your TV supports remote uninstall the tool will do it, if you gave the tool permission 

However I fully agree with you that setting the app up is a pain in the ass that's why it's possible to set part of the [Jellyfin configuration through the tool](https://github.com/PatrickSt1991/Samsung-Jellyfin-Installer?tab=readme-ov-file#-jellyfin-config)

You can pre set your IP address and a few more settings, if you are missing anything please let me know and I'll find out if I can put it in the tool.

**Comment by peaceful108** [comment]
> [@mjeshurun](https://github.com/mjeshurun) no unfortunately not, you can only over write the app with the new app if the author certificate matches (in most cases it won't cause the previous installation wasn't done by this tool, so I never bothered to build it in), when your TV supports remote uninstall the tool will do it, if you gave the tool permission
> 
> However I fully agree with you that setting the app up is a pain in the ass that's why it's possible to set part of the [Jellyfin configuration through the tool](https://github.com/PatrickSt1991/Samsung-Jellyfin-Installer?tab=readme-ov-file#-jellyfin-config)
> 
> You can pre set your IP address and a few more settings, if you are missing anything please let me know and I'll find out if I can put it in the tool.

Thank you for the explanation. 
I saw the pre-settings options. 
That's a very good and comfortable idea, but after I entered the API key, I don't see any users listed.

**Comment by PatrickSt1991** [comment]
Hmm that's wierd, cause I do the same and it's showing the user

<img width="560" height="273" alt="Image" src="https://github.com/user-attachments/assets/733a2561-a4d9-4403-bde1-b0ef91aea57f" />

this is piece of the code
`
                _httpClient.DefaultRequestHeaders.Clear();
                _httpClient.DefaultRequestHeaders.UserAgent.ParseAdd("SamsungJellyfinInstaller/1.0");
                _httpClient.DefaultRequestHeaders.Add("Authorization", $"MediaBrowser Token=\"{AppSettings.Default.JellyfinApiKey}\"");

                var url = $"http://{AppSettings.Default.JellyfinIP}/Users";
                Debug.WriteLine($"Attempting to load users from: {url}");

                using var response = await _httpClient.GetAsync(url);
`

it has http hardcoded are you using https maybe?

I'll also update the tool so that it will try to overwrite the existing Jellyfin app and one it fails the messages like the are shown now

**Comment by peaceful108** [comment]
Thank you for the screenshot. 
It helped me understand my mistake. 
Under Server IP I wrote "http://192.168.1.190", but it doesn't work with the "http://". Once I removed it and left only the IP number and port, the users showed up in the list.

**Comment by PatrickSt1991** [comment]
@mjeshurun thanks, already working on improving the tool, I really appreciate people like you reporting your issues;

<img width="550" height="215" alt="Image" src="https://github.com/user-attachments/assets/d839e674-649a-4fd0-a3cd-fea2f312fdb2" />
cause it will make it better and hopefully easier to use for future people

**Comment by peaceful108** [comment]
> [@mjeshurun](https://github.com/mjeshurun) thanks, already working on improving the tool, I really appreciate people like you reporting your issues;
> <img alt="Image" width="550" height="215" src="https://private-user-images.githubusercontent.com/18744743/513322252-d839e674-649a-4fd0-a3cd-fea2f312fdb2.png?jwt=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3NjI5NTQwMzcsIm5iZiI6MTc2Mjk1MzczNywicGF0aCI6Ii8xODc0NDc0My81MTMzMjIyNTItZDgzOWU2NzQtNjQ5YS00ZmQwLWEzY2QtZmVhMmYzMTJmZGIyLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNTExMTIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjUxMTEyVDEzMjIxN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTdjMDczY2E2MTJiYWNlMjQ4YzljZDQyM2VhZjM4ODlmODRhZTYxMDNhNjcxZmNmOWEyMDA4YTg5ZTI1ZWNmOGUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.DQQQ5gR50dRWftr8lXwL8D1mpdmr3w8GpmViwbWdSvc"> cause it will make it better and hopefully easier to use for future people

I'm happy to help with my small assistance. 
You are the one doing the hard work I don't know how to do myself :)
This http/s drop down chooser is more clear now. 
Thank you. 

I think the important addition now should be a way to update the app using the tool, without needing to re-login after the update.
But maybe it already works this way. I'll try to update again, next time I see there's an update to Jellyfin-Tizen.

**Comment by PatrickSt1991** [comment]
Totally agree, I need some time to think about a way how to do it, installing the app isn't the issue but my code needs to understand that we want to try and install the app first without deleting etc etc and when it fails it needs to try it's normal method.

Typing this makes it clearer already so pretty sure I'm able to write something that makes just that 😄

**Comment by peaceful108** [comment]
I'm not familiar with the programming requirements, but I can say that the previous method I used to install the app updates didn't require me to uninstall earlier app versions, so I didn't need to re-login after the update.

**Comment by peaceful108** [comment]
@PatrickSt1991 

On MacOS, do you, by chance, know how I can create a desktop shortcut that will run the ./Jellyfin2Samsung command from its folder location?
I was thinking to do do it with the Mac Automator app, but I'm getting an error when I run it. 

This is the flow I tried:

<img width="991" height="815" alt="Image" src="https://github.com/user-attachments/assets/106dc9a3-57c1-4765-9693-f1eb668d5263" />

And this is the error message I'm getting once your app opens:

<img width="989" height="815" alt="Image" src="https://github.com/user-attachments/assets/598d43e7-9fff-4318-a98a-ac2990f4f396" />

**Comment by PatrickSt1991** [comment]
@mjeshurun you should run ./post install.sh

**Comment by peaceful108** [comment]
> [@mjeshurun](https://github.com/mjeshurun) you should run ./post install.sh

I apologize, but I don't know how to incorporate that into the workflow I created.

**Comment by PatrickSt1991** [comment]
Well I'm not familiar with workflows on macOS but the tool I created isn't packaged as a bundle for macOS it's just an executable.

When the tool is running it will check the location it's running from and looks in the assets folder for the SDB client, so not sure what will happen with that flow

**Comment by peaceful108** [comment]
Ok, thanks. I’ll figure it out 🙏

**Comment by PatrickSt1991** [comment]
@mjeshurun are you okay with closing this issue as your problem is solved?

I'll open a new feature issue containing the app update and some more improvements I got planned.

#170

**Comment by peaceful108** [comment]
Well, the app still can’t update previous installs without removing the old version first, but  we can close it, if that’s what you prefer :)

**Comment by PatrickSt1991** [comment]
O haha true forgot it was s feature request and not an issue, let's leave it open

**Comment by PatrickSt1991** [comment]
@mjeshurun I've created this new build [v1.8.5.9-beta](https://github.com/PatrickSt1991/Samsung-Jellyfin-Installer/releases/tag/v1.8.5.9-beta)

<img width="612" height="732" alt="Image" src="https://github.com/user-attachments/assets/8f76b190-c774-40de-86d4-618dfb7ffb79" />
So right now per default the **Overwrite existing version** will be enabled, meaning the tool will try to install the newer version of the app, if it fails it fails silent but at the same time disabling the overwrite setting and tries again like it does right now.

For the Jellyfin server address it's now a combobox so it's more clear what the input should be

<img width="602" height="932" alt="Image" src="https://github.com/user-attachments/assets/7f37216a-d647-4616-9259-24cebbbc4d3f" />

**Comment by peaceful108** [comment]
Thanks for the update @PatrickSt1991 , 
I uninstalled the Jellyfin-Tizen app I already had on my TV and then install an older version with 1.8.5.9-beta.
The first install using 1.8.5.9-beta worked ok (because there was no Jellyfin app on the TV), but when I tried to update the app I just installed to one of the newer app versions, the installation failed and said I need to remove the previous install first.
So, I guess, updating an existing app installation is still not working.

**Comment by peaceful108** [comment]
Maybe this github project [tizen-app-installer-cli](https://github.com/elfpie/tizen-app-installer-cli) can explain how to implement Jellyfin-Tizen app updates. 
I tried it and it is able to update already installed Jellyfin-Tizen apps.
This method also doesn't require us to sign-in to our Samsung accounts for the installation to function.

**Comment by PatrickSt1991** [comment]
@mjeshurun can you send me the log files that were created ?

I know that project, the login windows has to do with your Tizen OS version, based on that you either need a samsung certificate to be created or not.

For newer models it all depends on whether or not the author certificate is a match, if it is, it will allow you to overwrite te existing.

**Comment by PatrickSt1991** [comment]
@mjeshurun are these the steps you took?

1. Wiped existing Jellyfin from the TV.
2. Openend up the tool and filled in the Server IP

<img width="553" height="45" alt="Image" src="https://github.com/user-attachments/assets/f45445b0-1f6a-4448-9403-22bfb72d7ed7" />

3. Installed Jellyfin (ex. Jellyfin-10.10.z)

<img width="545" height="235" alt="Image" src="https://github.com/user-attachments/assets/a3e17fb9-b1b2-42ac-8ed3-68e01889a719" />

4. Changed the Jellyfin version from the selection to a newer version

<img width="551" height="240" alt="Image" src="https://github.com/user-attachments/assets/c79c55e2-b7bd-4a12-8cf5-08ea410f4507" />

5. Tried to install Jellyfin (ex. Jellyfin-10.11.z)

Also can you tell m what TIzen OS your device is running or just included all the log files the tool is making I can extract it from there.

**Comment by peaceful108** [comment]
If I'm not mistaken, my Frame TV 2019 is running Tizen 5. 
Sorry for my explanation before. 
I almost did what you demonstrated in your photos, but instead of updating from Jellyfin 10.10.z.wgt to 10.11.z.wgt, I updated the Jellyfin 10.11.z version from an older release to a newer release.

**Comment by PatrickSt1991** [comment]
> If I'm not mistaken, my Frame TV 2019 is running Tizen 5. 
> Sorry for my explanation before. 
> I almost did what you demonstrated in your photos, but instead of updating from Jellyfin 10.10.z.wgt to 10.11.z.wgt, I updated the Jellyfin 10.11.z version from an older release to a newer release. 


But you did fill in the server ip right?

**Comment by peaceful108** [comment]
Yes. 
I did everything you mentioned. The only difference is that I was trying to update to a newer release and not between major versions.

**Comment by PatrickSt1991** [comment]
Check, so that's not really a bug, more like something the tool doesn't support yet.

If you fill in the Server IP address the tool will modify the config.json inside the wgt package, therefore it needs to resign the entire wgt package cause the existing signature won't match due to the modification.

In order to perform a resigning process we need a valid certificate from Samsung that's why you need to login the create that certificate.

So without the IP address modification the package will be able to overwrite cause the author certificates match (backed inside)

The packages are created by Jeppevinkel, so I'll take a look if I can reuse that existing certificate for the lower Tizen OS versions

**Comment by PatrickSt1991** [comment]
https://raw.githubusercontent.com/jeppevinkel/jellyfin-tizen-builds/master/tizencert.p12 = Author certificate -> 1234
tizen-distributor-signer.p12 = Distributor certificate -> tizenpkcs12passfordsigner

**Comment by PatrickSt1991** [comment]
@mjeshurun okay so I created another build [v1.8.6.0-beta](https://github.com/PatrickSt1991/Samsung-Jellyfin-Installer/releases/tag/v1.8.6.0-beta), if your Tizen OS is a version that doesn't requires device-profile.xml to be pushed and doesn't require the newest certificates it will try and use the tizen developer certificate and author certificate from Jeppevinkel, I did however had to change the password of the author.p12 cause my SDB Client only allows to send one password.

```
                    if (tizenVersion < certVersion && tizenVersion > pushVersion && selectedCertificate == "Jelly2Sams (default)")
                    {
                        selectedCertificate = "Jellyfin";
                        _appSettings.Certificate = selectedCertificate;
                        _appSettings.ChosenCertificates = new ExistingCertificates
                        {
                            Name = "Jellyfin",
                            Duid = tvDuid,
                            File = Path.Combine(AppSettings.CertificatePath, "Jellyfin", "author.p12")
                        };
                    }
```

The package now comes with a pre compiled Certificate folder containing the Jellyfin certificate.

Can't test it myself cause due to all the debugging I'm currently hitting the GitHub rate limit haha, need to wait until I'm allowed to do API calls again

**Comment by peaceful108** [comment]
Thank you @PatrickSt1991 ,
With 1.8.6.0 beta, updating the release worked! :)
FYI, I didn't fill my Jellyfin API or server IP address.
I will test again on the next Jellyfin-Tizen release, to confirm everything is working as it should.

**Comment by yo8aiv** [comment]
**IS there a way to empty the cache memory of the TV ?**, after testing a few versions of the jf app  my TV memory got filled up i dont really want to reset TV to defaults !!

.. i understand this version might help overwrite the old install .. but still empty memory is supposesd to be 3x times that about 70 - 150Mb.

**Comment by PatrickSt1991** [comment]
@yo8aiv To clear the cache on a Samsung TV, use the "Device Care" feature (Settings > Support > Device Care > Manage Storage) to clear individual app caches, or go to Settings > Apps to select and clear cache for specific apps. For older models lacking Device Care, you can unplug the TV for 30 seconds to perform a soft reset that clears the cache. 

https://www.samsung.com/au/support/tv-audio-video/clear-app-cache-and-data-on-your-samsung-tv/?srsltid=AfmBOoqFvUGJva3Vl8zl0ic0Jn9VIqeSSeHzP-Nxzu7VkCO3kuLAk47u

**Comment by yo8aiv** [comment]
> [@yo8aiv](https://github.com/yo8aiv) To clear the cache on a Samsung TV, use the "Device Care" feature (Settings > Support > Device Care > Manage Storage) to clear individual app caches, or go to Settings > Apps to select and clear cache for specific apps. For older models lacking Device Care, you can unplug the TV for 30 seconds to perform a soft reset that clears the cache. 
> 
> https://www.samsung.com/au/support/tv-audio-video/clear-app-cache-and-data-on-your-samsung-tv/?srsltid=AfmBOoqFvUGJva3Vl8zl0ic0Jn9VIqeSSeHzP-Nxzu7VkCO3kuLAk47u

thx for the quick answer, testing on an older UE43M5000 series ... so there are no  these options. i' ve been trough that docu it applies to new'er models. Guess i'd have to do a complete reset. .. unless there is a way trough Tizen sdk somehow !!. 
Great work. Cheers.

**Comment by PatrickSt1991** [comment]
@yo8aiv no Tizen SDK can't do stuff like that, sorry

**Comment by peaceful108** [comment]
Checked again and updating is working properly. 
Thank you very much! 🙏
Closing issue.
