### ISSUE TITLE
tizen.bat fails with users with space

### ISSUE THREAD

**Issue by nworbneb** [PatrickSt1991/Samsung-Jellyfin-Installer#3]
Installation fails, I think because there is a space in my Windows username.  I think the wgt filename needs wrapping in quotes when calling tizen.bat:

`
C:\tizen-studio\tools\ide\bin\tizen.bat package -t wgt -s custom -- C:\Users\User Name\AppData\Local\SamsungJellyfinInstaller\Downloads\Jellyfin-10.10.z.wgt
Output:
Error: No argument is allowed:
Name\AppData\Local\SamsungJellyfinInstaller\Downloads\Jellyfin-10.10.z.wgt
`

**Comment by PatrickSt1991** [comment]
Thanks letting me know, I'll fix it and make a new release

**Comment by PatrickSt1991** [comment]
@nworbneb fixed in [v1.4](https://github.com/PatrickSt1991/Samsung-Jellyfin-Installer/releases/tag/v1.4) feel free to test it out.

**Comment by nworbneb** [comment]
Thanks Patrick.

That's got the process a bit further.  It now trys to install but fails with:
`Check certificate error::Invalid certificate chain with certificate in signature.:<-3>`

I think certificates should be in place, I did already install the client manually previously.

![Image](https://github.com/user-attachments/assets/f01ab9f9-8a61-46dc-9722-9d061340441e)

BTW, "Download & Installeer" seems to be English/Dutch should be "Download & Install"

**Comment by nworbneb** [comment]
Ah I can see this might be expected as later tizen versions aren't supported.  I'll try substituting in my developer cert.

**Comment by PatrickSt1991** [comment]
What tizen version are you running? Cause i'm working on a fix for [Tizen 7 and up](https://github.com/PatrickSt1991/Samsung-Jellyfin-Installer/tree/tizen).

I've figured out the process Samsung is using for its [signing process](https://github.com/PatrickSt1991/Samsung-Jellyfin-Installer) now all I need to do is implement it in the code but they didn't make it easy 😄 

It bassicly requires the tool to generate a csr and push it to the Samsung api.

I'll also implement multi language functions, it's Dutch Indeed

**Comment by nworbneb** [comment]
Thanks Patrick.  This tool is going to be really useful.

My TV originally had an older Tizen version that did not require developer sign apps, but since then has updated to "2024" which I think is Tizen 8.0.

I've signed and installed the Jellyfin app ok in the past, but every time I need to dig out what commands to run, it's a bit of a pain.  So a one-click solution is much appreciated.

As I've already configured Tizen Studio, I have a valid certificate "Jellyfin".  Would it be possible, until automated, to be able to specify the certificate, either manually or by interogating the certificate manager?

![Image](https://github.com/user-attachments/assets/f8b133cb-7528-4281-b93d-76df993b2cca)

Great work so far!  Thanks

**Comment by PatrickSt1991** [comment]
Will implement it, good idea.

The user can either choose to go for the automatic option, or for it's already created certificate, I'm on holiday now so not sure when I'll get around to it but it's definitely going in the tool

Btw the new v1.5 version has localization;
English 
Danish 
Dutch 

Veel free to add your own language if you want to

**Comment by PatrickSt1991** [comment]
@nworbneb i've just created a beta release;
https://github.com/PatrickSt1991/Samsung-Jellyfin-Installer/releases/tag/v1.5.1-beta

That release should work with Tizen 7 and above, please be aware this version is untested cause I can't test it right now.

**Comment by nworbneb** [comment]
Thanks Patrick.

The only problem with the new beta is my TV is on a different VLAN so it won't find it.  I need to be able to specify the IP address manually.  Maybe have a manual IP option in the "Select TV" dropdown?  Once an IP is entered it can go and interogate to see if it finds a TV there.

Also, if I click "Download & Install" without selecting a TV it says "Downloading package..." but nothing happens.  I mean it probably downloaded it but then silently failed to install.  Perhaps disable the "Download & Install" button until a valid TV is selected in "Select TV"?

**Comment by PatrickSt1991** [comment]
Good points, I'll create sub items for those.

Indeed it silently fails cause before the download there is a check if the IP is filled.

Let me work those issues, I'll come back to you with a new build

**Comment by PatrickSt1991** [comment]
@nworbneb i've created a new build
https://github.com/PatrickSt1991/Samsung-Jellyfin-Installer/releases/tag/v1.5.2-beta

This option is now present;
![Image](https://github.com/user-attachments/assets/a11c12b9-68bf-4384-b7d4-3f687954966b)

when you choose that option this window will show
![Image](https://github.com/user-attachments/assets/1910d2bc-d0c1-4674-a410-097da779b879)

Also button "Download & Install" is now disabled and can only be activated if there is a device found and some parameters are filled, so the silent fail should be fixed

**Comment by nworbneb** [comment]
Thanks Patrick.

The manual IP aspect works.  It would be nice if it remembered the IP, effectively adding it to the drop down list so you don't have to dig it out next time.  If the drop down changed, for example, to "QE85Q80CATXXU (172.23.1.126)" it would show it's found a suitable device there.

But the certificate signing doesn't seemed to have worked.  It's gone through the motions to get to "Installing package on device..."

![Image](https://github.com/user-attachments/assets/4effbc45-9669-4775-a0fc-5fd12c9e43e1)

**Comment by nworbneb** [comment]
It seems to have generated a certificate "Jelly2Sams".  The "Jellyfin" one is the one I've previously used to do this manually.

![Image](https://github.com/user-attachments/assets/f170bfe7-8208-4e14-91ef-e5360486c6d5)

**Comment by PatrickSt1991** [comment]
Good news — we’re making real progress: the certificates are now being created and stored neatly in Certificate Manager.

To double-check everything, could you send me the following?

tizen-studio-data/profile/profiles.xml

All files in SamsungCertificates/Jelly2Sams/


With those in hand I can inspect both the generated certificates and the profile XML that Certificate Manager is using. My gut says we’re very close to cracking this Tizen nut.

As for having the tool remember your IP address, I’ll look into whether there’s a secure way to persist that information.

**Comment by nworbneb** [comment]
Thanks Patrick. I've emailed those files to you.

**Comment by PatrickSt1991** [comment]
Thanks! I've figured out what's wrong, the issue now lies in the .pwd file.

Tizen certificate-manager uses the pwd file to decrypt the p12 files.

It first I thought I could just store the plain generated password in the file and certificate-manager would be okay with it, unfortunately that's not working.

I have to work through the jar files in order to find out how they encrypt the password so the tool can mimic that process.

**Comment by PatrickSt1991** [comment]
@nworbneb I've just updated the beta release again, it now includes the hashing that certificate-manager uses.

The test run I did created legit certificates and implemented the certificate correct in certificate manager

**Comment by nworbneb** [comment]
Hi Patrick, same cert error as before.  I've emailed you files.

**Comment by PatrickSt1991** [comment]
Dam that sucks, i didn't receive a email.

Can you also screenshot the certificate-manager when it's on Jelly2Sams?

That way I can easily see if the certificates are read correctly by certificate-manager.

I'll hope to implement a option to use your own certificates as well today or tomorrow

**Comment by nworbneb** [comment]
cert manager is ok:

![Image](https://github.com/user-attachments/assets/0befd503-ce72-4a49-845d-f6b3f119319b)

**Comment by PatrickSt1991** [comment]
@nworbneb released a new [beta version 1.5.4](https://github.com/PatrickSt1991/Samsung-Jellyfin-Installer/releases/tag/v1.5.4-beta), containing fixes in the certificate chain.

**Comment by nworbneb** [comment]
Hmm, I'm still getting the same "Invalid format of certificate in signature" error with 1.5.4 final.

All files in Jelly2Sams are all from a few minutes ago.

Certificate looks ok in cert manager:

![Image](https://github.com/user-attachments/assets/1129bead-eaa8-44cb-95b5-bd022ee3601c)

I can sign and install manually ok:

```
C:\Users\User Name>c:\tizen-studio\tools\ide\bin\tizen.bat package -t wgt -s Jellyfin -- "c:\Users\Use Name\AppData\Local\SamsungJellyfinInstaller\Downloads\Jellyfin-10.10.z.wgt"
Author certficate: C:\Users\User Name\SamsungCertificate\Jellyfin\author.p12
Distributor1 certificate : C:\Users\User Name\SamsungCertificate\Jellyfin\distributor.p12
Package( C:\Users\User Name\AppData\Local\SamsungJellyfinInstaller\Downloads\Jellyfin-10.10.z.wgt ) is created successfully.

C:\Users\User Name>c:\tizen-studio\tools\ide\bin\tizen.bat install -n "c:\Users\User Name\AppData\Local\SamsungJellyfinInstaller\Downloads\Jellyfin-10.10.z.wgt" -t QE85Q80CATXXU
Transferring the package...
Transferred the package: C:\Users\User Name\AppData\Local\SamsungJellyfinInstaller\Downloads\Jellyfin-10.10.z.wgt -> /home/owner/share/tmp/sdk_tools/tmp
Installing the package...
--------------------
Platform log view
--------------------
install AprZAARz4r.Jellyfin
package_path /home/owner/share/tmp/sdk_tools/tmp/Jellyfin-10.10.z.wgt
app_id[AprZAARz4r.Jellyfin] install start
app_id[AprZAARz4r.Jellyfin] installing[10]
app_id[AprZAARz4r.Jellyfin] installing[20]
app_id[AprZAARz4r.Jellyfin] installing[30]
app_id[AprZAARz4r.Jellyfin] installing[40]
app_id[AprZAARz4r.Jellyfin] installing[51]
app_id[AprZAARz4r.Jellyfin] installing[61]
app_id[AprZAARz4r.Jellyfin] installing[71]
app_id[AprZAARz4r.Jellyfin] installing[81]
app_id[AprZAARz4r.Jellyfin] installing[91]
app_id[AprZAARz4r.Jellyfin] installing[100]
app_id[AprZAARz4r.Jellyfin] install completed
spend time for wascmd is [13585]ms
Installed the package: Id(AprZAARz4r.Jellyfin)
Tizen application is successfully installed.
Total time: 00:00:17.199
```
But not with the Jelly2Sams:

```
C:\Users\User Name>c:\tizen-studio\tools\ide\bin\tizen.bat package -t wgt -s Jelly2Sams -- "c:\Users\User Name\AppData\Local\SamsungJellyfinInstaller\Downloads\Jellyfin-10.10.z.wgt"
Author certficate: C:\Users\User Name\SamsungCertificate\Jelly2Sams\author.p12
Distributor1 certificate : C:\Users\User Name\SamsungCertificate\Jelly2Sams\distributor.p12
Package( C:\Users\User Name\AppData\Local\SamsungJellyfinInstaller\Downloads\Jellyfin-10.10.z.wgt ) is created successfully.

C:\Users\User Name>c:\tizen-studio\tools\ide\bin\tizen.bat install -n "c:\Users\User Name\AppData\Local\SamsungJellyfinInstaller\Downloads\Jellyfin-10.10.z.wgt" -t QE85Q80CATXXU
Transferring the package...
Transferred the package: C:\Users\User Name\AppData\Local\SamsungJellyfinInstaller\Downloads\Jellyfin-10.10.z.wgt -> /home/owner/share/tmp/sdk_tools/tmp
Installing the package...
--------------------
Platform log view
--------------------
install AprZAARz4r.Jellyfin
package_path /home/owner/share/tmp/sdk_tools/tmp/Jellyfin-10.10.z.wgt
app_id[AprZAARz4r.Jellyfin] install start
app_id[AprZAARz4r.Jellyfin] installing[10]
app_id[AprZAARz4r.Jellyfin] installing[20]
app_id[AprZAARz4r.Jellyfin] install failed[118, -12], reason: Check certificate error : :Invalid format of certificate in signature.:<-2>
spend time for wascmd is [5872]ms
Failed to install Tizen application.
Total time: 00:00:09.534
```

I then signed the same wgt file with "Jellyfin" cert and it installed ok.

**Comment by PatrickSt1991** [comment]
@nworbneb that bug is now solved in [v1.5.6](https://github.com/PatrickSt1991/Samsung-Jellyfin-Installer/releases/tag/v1.5.6)

The TizenStudio installer doesn't include the certificate-manager, so it was failing with wrong certificates.

Also changed the order so, first lookup is c:\tizen-studio, cause most people already got that installed

**Comment by nworbneb** [comment]
Still the same in 1.5.6.  All the files in "Jelly2Sam" are new, my original cert "Jellyfin" signs it without issue.

```
Installing the package...
--------------------
Platform log view
--------------------
install AprZAARz4r.Jellyfin
package_path /home/owner/share/tmp/sdk_tools/tmp/Jellyfin-10.10.z.wgt
app_id[AprZAARz4r.Jellyfin] install start
app_id[AprZAARz4r.Jellyfin] installing[10]
app_id[AprZAARz4r.Jellyfin] installing[20]
app_id[AprZAARz4r.Jellyfin] install failed[118, -12], reason: Check certificate error : :Invalid format of certificate in signature.:<-2>
spend time for wascmd is [6189]ms
Failed to install Tizen application.
Total time: 00:00:09.875
```

Also, cert issues aside, does it need me to login to Samsung every time?  These certs are valid for a year.

**Comment by PatrickSt1991** [comment]
@nworbneb okay question, can you check on your TV what you DUID is?
"Menu > Support > Contact Samsung".

That should show you your DUID

I know the certs are valid for a year, I'm working on extending the tool so you can choose already created or valid certificates, if the choosen certificate is valid you can pick it from the list and it will use that one and you won't have to login every time.

![Image](https://github.com/user-attachments/assets/f37b298e-1da3-48c5-aa10-98d7f75c43ec)

However I need to tackle this certificate issue first before I can finish coding the settings page.

**Comment by nworbneb** [comment]
Cool, thanks Patrick

I've sent you an email with DUID and zip of Jelly2Sams folder.

**Comment by nworbneb** [comment]
What I do notice is that in my working cert ("Jellyfin") the device-profile.xml has my DUID `<TestDevice>EXCJ*******NU</TestDevice>`

But "Jellyfin2Sam" has the name of my TV `<TestDevice>QE85Q80CATXXU</TestDevice>`

**Comment by PatrickSt1991** [comment]
@nworbneb  Thank you! The issue turned out to be that the certificate was signed using the device name instead of the device DUID.

I reverse-engineered the Device Manager to figure this out. I'm not entirely sure if the same approach will work on Tizen 8, but it does work on Tizen 5.

[v1.5.7](https://github.com/PatrickSt1991/Samsung-Jellyfin-Installer/releases/tag/v1.5.7)

**Comment by nworbneb** [comment]
Still not working.... but the error is different, which I'll take as a step forward!

```
install AprZAARz4r.Jellyfin
package_path /home/owner/share/tmp/sdk_tools/tmp/Jellyfin-10.10.z.wgt
app_id[AprZAARz4r.Jellyfin] install start
app_id[AprZAARz4r.Jellyfin] installing[10]
app_id[AprZAARz4r.Jellyfin] installing[20]
app_id[AprZAARz4r.Jellyfin] install failed[118, -11], reason: Author certificate not match :
spend time for wascmd is [8334]ms
Failed to install Tizen application.
Total time: 00:00:12.286
```

**Comment by PatrickSt1991** [comment]
@nworbneb you probably got the Jellyfin app already installed, you did that with a different Author.ps12 certificate.

If you delete the app from the tv and try again, my guess is, it should work..

**Comment by nworbneb** [comment]
Thanks Patrick, it is now working.

For reference I deleted remotely, which is perhaps a good idea each time for robustness.

`c:\tizen-studio\tools\ide\bin\tizen.bat uninstall -t QE85Q80CATXXU -p AprZAARz4r.Jellyfin`

**Comment by PatrickSt1991** [comment]
Great news, I'll add a checkbox on the settings page.

So the user can decide if he wants to delete previous installments
