### ISSUE TITLE
something missing

### ISSUE THREAD

**Issue by Edwinhpi** [PatrickSt1991/Samsung-Jellyfin-Installer#35]
I am new to this. but I am trying to install Jellyfin on my Samsung 65Q95TCL. Everything is automatically recognized and the TV is in developer mode. But during the installation I get the following message.
![Image](https://github.com/user-attachments/assets/e9780538-b0b3-4b7e-a3de-e48e0727f7fc)
 It seems like I am missing something. Can someone help me with this

**Comment by PatrickSt1991** [comment]
There seems to be a bug in the application, cause it can't find a required sdk-utils-core.jar file.

Can you please check if the file exists at this location?
C:\Users\IntelNuc\AppData\Local\Programs\TizenStudioCli\tools\library\sdk-utils-core.jar

If not well need to check if the required tizen tools were installed correct if it is i need to fix the code

**Comment by Edwinhpi** [comment]
Thnx for the fast reply. I find out that the tizen tools was not been correct installed. Reinstalling tizen tools and your app installed jellyfin on my tv

**Comment by PatrickSt1991** [comment]
I've also implemented additional check is the code, so thanks for creating the issue.

Glad to hear it's working now

**Comment by lukehsiao** [comment]
I still see this issue:
<img width="505" height="285" alt="Image" src="https://github.com/user-attachments/assets/0e474c07-8f9b-40c1-ab12-8e7f04bd7cec" />

However, unlike the original poster, the file is present

<img width="1108" height="356" alt="Image" src="https://github.com/user-attachments/assets/34127863-ca47-4c61-a6e4-cc1113591253" />

Anything I can do to resolve this?

**Comment by PatrickSt1991** [comment]
@lukehsiao this usually happens when somewhere in the installation process something went wrong.

Can you remove these folders;
C:\Users\Luke Hsiao\AppData\Local\Programs\TizenStudioCli
C:\Users\Luke Hsiao\AppData\Local\Programs\TizenStudioCli-data

and try the tool again?

if the issue still persists well debug from there

also just released [v1.8.0](https://github.com/PatrickSt1991/Samsung-Jellyfin-Installer/releases/tag/v1.8.0-beta-2) containing major code and styling overhaul.

**Comment by lukehsiao** [comment]
Yes, I tried that many times to no avail.

All the same result. 

I ended up just doing things myself, manually.

**Comment by PatrickSt1991** [comment]
@lukehsiao a shit I just now noticed that you have a space in your username.

That's what's causing the error 😞

As you already did things manually it won't help you anymore I guess, but hopefully others will.

**Comment by lukehsiao** [comment]
> @lukehsiao a shit I just now noticed that you have a space in your username.
> 
> That's what's causing the error 😞
> 
> As you already did things manually it won't help you anymore I guess, but hopefully others will.

I was wondering why the error message was split into multiple lines lime that! Thanks for making a new issue. When it comes time to upgrade, this program would definitely be the easier path for me, too.
